vim.g.mapleader = ' '

require('plugins.treesitter')
require('plugins.lsp')
require('plugins.oil')
require('plugins.telescope')
require('plugins.mason')
require('plugins.snippets')
require('plugins.git')
require('plugins.autocomplete')
require('plugins.autopairs')
require('plugins.surround')
require('plugins.remote-neovim')
require('plugins.markdown')
require('plugins.latex')
require('plugins.colorscheme')
require('plugins.lualine')
require('keymaps.keymaps')
require('options.options')
