unbind C-b
unbind %
unbind '"'
unbind d
set-option -g prefix C-space
set-option -g default-shell /bin/bash

unbind r
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

set-option -g status-position top
set-option -g status-justify absolute-centre
set-option -g status-style "bg=default"
set-option -g window-status-current-style "fg=blue bg=default bold"
set-option -g status-right "%a %d %b %I:%M %p"
set-option -g status-left ""

set -g default-terminal "tmux-256color"
set -as terminal-overrides ',*:Tc'
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
setw -g mode-keys vi

bind-key c new-window -c "#{pane_current_path}"
bind-key | split-window -h -c "#{pane_current_path}"
bind-key 'v' split-window -v -c "#{pane_current_path}"
bind-key 'q' detach-client

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind -r C-k resize-pane -U
bind -r C-j resize-pane -D
bind -r C-h resize-pane -L
bind -r C-l resize-pane -R
